DROP TABLE PARTNERRANK CASCADE CONSTRAINTS;
DROP TABLE PARTNER CASCADE CONSTRAINTS;
DROP TABLE ADMIN_RANK CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE_LIST CASCADE CONSTRAINTS;
DROP TABLE USERPASS_EMP CASCADE CONSTRAINTS;
DROP TABLE USERPASS_PARTNER CASCADE CONSTRAINTS;
DROP TABLE CAMPAIGNSTATUS CASCADE CONSTRAINTS;
DROP TABLE CAMPAIGN CASCADE CONSTRAINTS;
DROP TABLE CAMPAIGNLEVEL1 CASCADE CONSTRAINTS;
DROP TABLE CAMPAIGNLEVEL2 CASCADE CONSTRAINTS;
DROP TABLE CAMPAIGNLEVEL3 CASCADE CONSTRAINTS;
DROP TABLE CAMPAIGNLEVEL4 CASCADE CONSTRAINTS;

CREATE TABLE PARTNERRANK(
        PRANK NUMBER(5),
        PRANKSTATUS VARCHAR2(25),

        PRIMARY KEY(PRANK)
);

CREATE TABLE PARTNER (
        PNO VARCHAR2(10),
        PNAME VARCHAR2(80),
        PCONTACTPERSON VARCHAR2(80),
        PMAIL VARCHAR2(80),
        PPHONE VARCHAR2(15),
        PADDRESS VARCHAR2(30),
        PRANK NUMBER(5),

        PRIMARY KEY(PNO),
        FOREIGN KEY (PRANK) REFERENCES PARTNERRANK
);

CREATE TABLE ADMIN_RANK(
        EADMINRANK NUMBER (5),
        ARANKSTATUS VARCHAR2(10),

        PRIMARY KEY (EADMINRANK)
);

CREATE TABLE EMPLOYEE_LIST(
        ENO VARCHAR2(10),
        ENAME VARCHAR2(80),
        EMAIL VARCHAR2 (80),
        EPHONE VARCHAR2 (25),
        EADMINRANK NUMBER(5),
        ESTATUS VARCHAR2(20),

        PRIMARY KEY (ENO),
        FOREIGN KEY (EADMINRANK) REFERENCES ADMIN_RANK
);


CREATE TABLE USERPASS_EMP (
	USERNAME VARCHAR2 (30),
	PASSWORD VARCHAR2 (30),
        ENO VARCHAR2 (10),

	PRIMARY KEY(USERNAME, PASSWORD),
        FOREIGN KEY (ENO) REFERENCES EMPLOYEE_LIST
);

CREATE TABLE USERPASS_PARTNER (
	USERNAME VARCHAR2 (30),
	PASSWORD VARCHAR2 (30),
        PNO VARCHAR2 (10),

	PRIMARY KEY(USERNAME, PASSWORD),
        FOREIGN KEY (PNO) REFERENCES PARTNER
);

CREATE TABLE CAMPAIGNSTATUS (
	CSTATUS NUMBER (10),
	CSTATUSDESCRIPTION VARCHAR2 (30),
	PRIMARY KEY (CSTATUS)
);


CREATE TABLE CAMPAIGN (
	CNO VARCHAR2 (10),
	PNAME VARCHAR2 (30),
	CCONTACT VARCHAR2 (30),
	ENAME VARCHAR2 (80),
	CSTARTDATE DATE,
	CENDDATE DATE,
	CSTATUS NUMBER(10),
	
	PRIMARY KEY (CNO),
        FOREIGN KEY (ENAME) REFERENCES EMPLOYEE_LIST,
        FOREIGN KEY (CSTATUS) REFERENCES CAMPAIGNSTATUS
);

CREATE TABLE CAMPAIGNLEVEL1 (
	CNO VARCHAR2 (10),
	CLEVEL1START VARCHAR2 (30),
	CLEVEL1END VARCHAR2 (30),

	PRIMARY KEY (CNO, CLEVEL1START),
        FOREIGN KEY (CNO) REFERENCES CAMPAIGN
);

CREATE TABLE CAMPAIGNLEVEL2 (
	CNO VARCHAR2 (10),
	CLEVEL2START VARCHAR2 (30),
	CLEVEL2END VARCHAR2 (30),

	PRIMARY KEY (CNO, CLEVEL2START),
        FOREIGN KEY (CNO) REFERENCES CAMPAIGN
);

CREATE TABLE CAMPAIGNLEVEL3 (
	CNO VARCHAR2 (10),
	CLEVEL3START VARCHAR2 (30),
	CLEVEL3END VARCHAR2 (30),

	PRIMARY KEY (CNO, CLEVEL3START),
        FOREIGN KEY (CNO) REFERENCES CAMPAIGN
);

CREATE TABLE CAMPAIGNLEVEL4 (
	CNO VARCHAR2 (10),
	CLEVEL4START VARCHAR2 (30),
	CLEVEL4END VARCHAR2 (30),

	PRIMARY KEY (CNO, CLEVEL4START),
        FOREIGN KEY (CNO) REFERENCES CAMPAIGN
);
